In [ ]:
'''Set 6 (Healthcare Data Analysis)
NumPy (Intermediate)
 Patient vitals (heart rate) are stored for 60 patients over 24 hours in a NumPy array.
Task:
Compute hourly average heart rate


Detect abnormal readings outside the normal range


Replace missing values using forward fill logic
'''

In [5]:
import numpy as np
vitals = np.random.randint(60,120, size = (60,24))
print(vitals)

[[ 99  92 113 ...  75  65  70]
 [ 91 116  95 ...  78  86 101]
 [ 78  65 108 ... 113  68 101]
 ...
 [106  71  74 ... 100  84  70]
 [ 76  77  96 ...  97  77  78]
 [ 98 113 105 ... 104  61 101]]


In [7]:
hour_avg = vitals.mean(axis =0)
print(hour_avg)

[88.1        88.55       93.15       86.28333333 90.31666667 91.06666667
 89.         90.58333333 93.48333333 89.4        88.25       86.13333333
 89.78333333 91.63333333 84.48333333 91.8        90.55       85.8
 88.9        89.11666667 87.13333333 87.11666667 86.61666667 86.98333333]


In [8]:
low ,high = 60,100
abnormal_mask = (vitals<low) | (vitals > high)
abnormal_positions = np.where(abnormal_mask)
print("Total abnormal readings:",abnormal_mask.sum())
print("Patient index:",abnormal_positions[0])
print("Hour index:",abnormal_positions[1])


Total abnormal readings: 433
Patient index: [ 0  0  0  0  0  1  1  1  1  1  1  2  2  2  2  2  2  2  2  3  3  3  3  3
  3  4  4  4  4  4  4  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  6  7
  7  7  7  7  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9 10 10 10 10 10
 10 10 11 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 13 13
 13 13 13 13 13 13 14 14 14 14 14 14 14 14 14 14 14 14 15 15 15 15 15 15
 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 18 18 18 18 18 18 18 18 18
 18 18 19 19 19 19 19 19 19 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21
 21 22 22 22 22 22 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24
 24 25 25 25 25 25 25 25 25 25 25 26 26 26 27 27 27 27 27 27 28 28 28 28
 28 28 28 28 29 29 29 29 29 29 29 30 30 30 30 30 30 30 30 30 31 31 31 31
 32 32 32 32 32 32 33 33 33 33 33 33 34 34 34 34 34 34 34 34 35 35 35 35
 35 36 36 36 37 37 37 37 37 37 37 37 38 38 38 38 38 38 38 39 39 39 39 39
 39 40 40 40 40 40 40 40 40 40 40 41 41 41 41 41 41 41 41 41 41 41 42 42
 42 42 