In [ ]:
'''NumPy (Intermediate)
 A retail company records daily sales of 5 products across 30 days in a 2D NumPy array of shape (30, 5).
 Due to a system error, negative values appear in the dataset.
Task:
Replace negative values with 0


Compute the average weekly sales per product (assume 7 days = 1 week)


Identify the product with the highest average weekly sales'''

In [7]:
import numpy as np
sales = np.random.randint(-20,200,size=(30,5))
print(sales)

[[ 57  27 122  42 153]
 [ 53  27  49 188  87]
 [131  -4 191  75   3]
 [ 55  75  52  59 137]
 [  9  49  87 175  40]
 [ 76 188 126 128  54]
 [ 79 161  19 198 133]
 [ 93  -5 184 129  -7]
 [ 41  68 -10  80  39]
 [ 67  31  52 133 143]
 [158  73 116 121 186]
 [ 72  38  86 155  15]
 [171 159  90  98  70]
 [  0 182 118   5 163]
 [160 190 160 -19  72]
 [159 160 190 151  93]
 [101 145 146  95 179]
 [115 182  -7 147  71]
 [ 67  40 -15  76  59]
 [139 180  51 141  42]
 [ 24 132 140  81 155]
 [173  25  88 112   4]
 [191  41  73  25  51]
 [ 50 151  74   6 111]
 [ 76  11 100  -6  75]
 [127  28 184 121 139]
 [110 188 -12 136 158]
 [181 123  12  -3 105]
 [ 16  88 149  82  18]
 [125  32 -19  70 105]]


In [8]:
sales[sales<0]=0
print(sales)

[[ 57  27 122  42 153]
 [ 53  27  49 188  87]
 [131   0 191  75   3]
 [ 55  75  52  59 137]
 [  9  49  87 175  40]
 [ 76 188 126 128  54]
 [ 79 161  19 198 133]
 [ 93   0 184 129   0]
 [ 41  68   0  80  39]
 [ 67  31  52 133 143]
 [158  73 116 121 186]
 [ 72  38  86 155  15]
 [171 159  90  98  70]
 [  0 182 118   5 163]
 [160 190 160   0  72]
 [159 160 190 151  93]
 [101 145 146  95 179]
 [115 182   0 147  71]
 [ 67  40   0  76  59]
 [139 180  51 141  42]
 [ 24 132 140  81 155]
 [173  25  88 112   4]
 [191  41  73  25  51]
 [ 50 151  74   6 111]
 [ 76  11 100   0  75]
 [127  28 184 121 139]
 [110 188   0 136 158]
 [181 123  12   0 105]
 [ 16  88 149  82  18]
 [125  32   0  70 105]]


In [9]:
weeks = sales[:28].reshape(4,7,5)
print(weeks)

[[[ 57  27 122  42 153]
  [ 53  27  49 188  87]
  [131   0 191  75   3]
  [ 55  75  52  59 137]
  [  9  49  87 175  40]
  [ 76 188 126 128  54]
  [ 79 161  19 198 133]]

 [[ 93   0 184 129   0]
  [ 41  68   0  80  39]
  [ 67  31  52 133 143]
  [158  73 116 121 186]
  [ 72  38  86 155  15]
  [171 159  90  98  70]
  [  0 182 118   5 163]]

 [[160 190 160   0  72]
  [159 160 190 151  93]
  [101 145 146  95 179]
  [115 182   0 147  71]
  [ 67  40   0  76  59]
  [139 180  51 141  42]
  [ 24 132 140  81 155]]

 [[173  25  88 112   4]
  [191  41  73  25  51]
  [ 50 151  74   6 111]
  [ 76  11 100   0  75]
  [127  28 184 121 139]
  [110 188   0 136 158]
  [181 123  12   0 105]]]


In [10]:
weekly_sales = weeks.sum(axis=1)
print(weekly_sales)

[[ 460  527  646  865  607]
 [ 602  551  646  721  616]
 [ 765 1029  687  691  671]
 [ 908  567  531  400  643]]


In [54]:
avg_weekly_sales = weekly_sales.mean(axis=0)
print(avg_weekly_sales)

[554.25 678.   660.   537.5  588.5 ]


In [55]:
best_product_index = np.argmax(avg_weekly_sales)
print(best_product_index)

1


In [56]:
print("Average weekly sales per product:", avg_weekly_sales)
print("Highest avrage weekly sales product:",best_product_index + 1)

Average weekly sales per product: [554.25 678.   660.   537.5  588.5 ]
Highest avrage weekly sales product: 2
