In [ ]:
'''NumPy (Intermediate)
 A retail company records daily sales of 5 products across 30 days in a 2D NumPy array of shape (30, 5).
 Due to a system error, negative values appear in the dataset.
Task:
Replace negative values with 0


Compute the average weekly sales per product (assume 7 days = 1 week)


Identify the product with the highest average weekly sales'''

In [46]:
import numpy as np
sales = np.random.randint(-20,200,size=(30,5))
print(sales)

[[ 79  45  80  61 198]
 [-17  97  66  33  -2]
 [ 77 183  24 169  99]
 [141  -1 172  19  -6]
 [ 11  95  99 137 -14]
 [181 115  17 177 131]
 [ -2  88 120   9   6]
 [-13 198 103  83  77]
 [151  55 177  34 128]
 [-12  51 158 179 111]
 [167  35 194 154  12]
 [137 180  71  66 144]
 [169  91  43 199   4]
 [ 62 165 110  67 184]
 [ 83  93   1 122   1]
 [ 47 107 112 153 148]
 [130 192  40  45  15]
 [ 40 193 122   4  12]
 [153 118 140  27  62]
 [ 55  52   0  46  42]
 [125 160  72  70 138]
 [116  46  86  10 187]
 [ 18  43  42  55 110]
 [-14  81 106  -7 108]
 [ 88  62  93  99 123]
 [ 57 -13 179 119 117]
 [ 85  39 101  13 -12]
 [ 45 128 112 -20 197]
 [ 52  95 161 102 -10]
 [190  -5 165  77  28]]


In [47]:
sales[sales<0]=0
print(sales)

[[ 79  45  80  61 198]
 [  0  97  66  33   0]
 [ 77 183  24 169  99]
 [141   0 172  19   0]
 [ 11  95  99 137   0]
 [181 115  17 177 131]
 [  0  88 120   9   6]
 [  0 198 103  83  77]
 [151  55 177  34 128]
 [  0  51 158 179 111]
 [167  35 194 154  12]
 [137 180  71  66 144]
 [169  91  43 199   4]
 [ 62 165 110  67 184]
 [ 83  93   1 122   1]
 [ 47 107 112 153 148]
 [130 192  40  45  15]
 [ 40 193 122   4  12]
 [153 118 140  27  62]
 [ 55  52   0  46  42]
 [125 160  72  70 138]
 [116  46  86  10 187]
 [ 18  43  42  55 110]
 [  0  81 106   0 108]
 [ 88  62  93  99 123]
 [ 57   0 179 119 117]
 [ 85  39 101  13   0]
 [ 45 128 112   0 197]
 [ 52  95 161 102   0]
 [190   0 165  77  28]]


In [48]:
weeks = sales[:28].reshape(4,7,5)
print(weeks)

[[[ 79  45  80  61 198]
  [  0  97  66  33   0]
  [ 77 183  24 169  99]
  [141   0 172  19   0]
  [ 11  95  99 137   0]
  [181 115  17 177 131]
  [  0  88 120   9   6]]

 [[  0 198 103  83  77]
  [151  55 177  34 128]
  [  0  51 158 179 111]
  [167  35 194 154  12]
  [137 180  71  66 144]
  [169  91  43 199   4]
  [ 62 165 110  67 184]]

 [[ 83  93   1 122   1]
  [ 47 107 112 153 148]
  [130 192  40  45  15]
  [ 40 193 122   4  12]
  [153 118 140  27  62]
  [ 55  52   0  46  42]
  [125 160  72  70 138]]

 [[116  46  86  10 187]
  [ 18  43  42  55 110]
  [  0  81 106   0 108]
  [ 88  62  93  99 123]
  [ 57   0 179 119 117]
  [ 85  39 101  13   0]
  [ 45 128 112   0 197]]]


In [49]:
weekly_sales = weeks.sum(axis=1)
print(weekly_sales)

[[489 623 578 605 434]
 [686 775 856 782 660]
 [633 915 487 467 418]
 [409 399 719 296 842]]


In [54]:
avg_weekly_sales = weekly_sales.mean(axis=0)
print(avg_weekly_sales)

[554.25 678.   660.   537.5  588.5 ]


In [55]:
best_product_index = np.argmax(avg_weekly_sales)
print(best_product_index)

1


In [56]:
print("Average weekly sales per product:", avg_weekly_sales)
print("Highest avrage weekly sales product:",best_product_index + 1)

Average weekly sales per product: [554.25 678.   660.   537.5  588.5 ]
Highest avrage weekly sales product: 2
