In [1]:
'''Set 2 (Employee Performance System)
NumPy (Intermediate)
 An HR system stores employee performance ratings (scale 1–5) for 100 employees over 4 quarters in a NumPy array.
Task:
Normalize the ratings using min-max normalization


Calculate the average rating per employee


Identify employees whose average rating is above the company mean
'''

'Set 2 (Employee Performance System)\nNumPy (Intermediate)\n An HR system stores employee performance ratings (scale 1–5) for 100 employees over 4 quarters in a NumPy array.\nTask:\nNormalize the ratings using min-max normalization\n\n\nCalculate the average rating per employee\n\n\nIdentify employees whose average rating is above the company mean\n'

In [2]:
import numpy as np
ratings = np.random.randint(1,6,size =(100,4))
print(ratings)

[[5 3 4 4]
 [1 1 1 5]
 [4 1 4 5]
 [1 5 3 1]
 [4 1 1 1]
 [3 5 4 2]
 [3 5 5 1]
 [2 1 5 2]
 [2 1 3 5]
 [4 3 4 5]
 [1 2 3 2]
 [4 5 3 1]
 [4 1 5 2]
 [2 1 1 4]
 [3 3 3 4]
 [3 4 4 1]
 [3 3 5 2]
 [3 5 1 1]
 [3 1 4 1]
 [5 5 5 5]
 [4 5 1 5]
 [4 4 4 1]
 [2 5 1 3]
 [4 5 4 4]
 [1 3 5 3]
 [4 5 3 1]
 [2 3 1 1]
 [2 5 4 3]
 [5 4 2 1]
 [5 4 3 4]
 [2 2 2 2]
 [3 5 4 1]
 [5 4 5 3]
 [2 4 1 2]
 [2 3 4 5]
 [3 2 4 3]
 [4 3 3 4]
 [3 5 1 4]
 [2 4 3 4]
 [1 2 1 1]
 [2 3 1 3]
 [1 4 3 4]
 [2 5 5 2]
 [5 3 3 2]
 [3 5 4 4]
 [3 2 5 1]
 [3 1 4 3]
 [3 5 1 5]
 [2 5 4 4]
 [1 1 1 5]
 [2 3 3 3]
 [1 4 2 1]
 [1 5 1 5]
 [1 5 5 3]
 [1 1 3 3]
 [3 3 3 2]
 [1 2 5 5]
 [4 5 5 2]
 [4 5 4 4]
 [5 2 4 1]
 [2 2 2 5]
 [4 3 3 3]
 [4 4 1 2]
 [5 1 3 5]
 [5 4 5 4]
 [3 3 5 1]
 [4 1 3 1]
 [5 1 5 2]
 [1 3 4 2]
 [1 5 5 2]
 [5 5 2 5]
 [3 5 4 4]
 [4 3 2 2]
 [1 5 2 3]
 [5 1 4 5]
 [3 1 4 1]
 [1 1 3 1]
 [2 4 3 1]
 [1 1 4 5]
 [3 2 4 5]
 [3 3 1 4]
 [5 2 4 4]
 [2 3 2 1]
 [5 2 1 5]
 [2 1 5 5]
 [3 3 5 4]
 [5 1 3 4]
 [4 2 3 4]
 [1 1 5 3]
 [3 4 2 4]
 [2 1 4 3]

In [5]:
min = ratings.min()
print(min)
max = ratings.max()
print(max)

1
5


In [3]:
normalize = (ratings-min)/(max-min)
print(normalize)

[[0.75 0.75 0.25 0.5 ]
 [0.25 0.5  1.   0.25]
 [1.   0.   0.25 0.5 ]
 [0.75 0.5  0.75 0.25]
 [1.   0.5  0.   0.  ]
 [0.75 0.75 0.75 0.5 ]
 [0.5  0.25 0.75 0.5 ]
 [0.75 0.   0.75 1.  ]
 [0.25 0.75 0.   1.  ]
 [0.25 0.5  0.25 0.  ]
 [1.   1.   1.   0.5 ]
 [1.   0.75 1.   0.5 ]
 [0.   1.   1.   1.  ]
 [0.5  0.75 1.   0.25]
 [0.5  0.25 0.   0.5 ]
 [1.   0.   0.5  0.25]
 [1.   0.75 0.75 0.75]
 [0.75 0.75 0.75 0.5 ]
 [0.25 1.   0.75 0.5 ]
 [0.75 0.25 0.   1.  ]
 [0.75 0.   0.75 1.  ]
 [0.5  0.25 0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.5  0.25]
 [0.25 1.   1.   0.  ]
 [0.   0.75 1.   0.5 ]
 [0.   0.75 0.75 1.  ]
 [0.25 0.25 0.25 0.75]
 [1.   0.   0.25 0.25]
 [0.   1.   0.25 0.75]
 [1.   1.   0.5  0.5 ]
 [0.25 0.5  0.5  0.5 ]
 [0.5  0.5  0.25 0.5 ]
 [0.5  0.5  1.   0.5 ]
 [1.   0.5  0.   0.  ]
 [0.   0.   0.25 1.  ]
 [0.5  0.5  0.25 0.75]
 [0.   0.75 0.25 1.  ]
 [0.25 1.   0.   0.25]
 [0.5  0.25 0.5  0.25]
 [0.5  0.75 0.25 0.5 ]
 [0.75 0.5  0.25 1.  ]
 [0.75 0.   0.25 0.5 ]
 [0.5  0.25

In [11]:
avg_per_emp = ratings.mean(axis=1)
print(avg_per_emp)

[3.25 3.   2.75 3.25 2.5  3.75 3.   3.5  3.   2.   4.5  4.25 4.   3.5
 2.25 2.75 4.25 3.75 3.5  3.   3.5  1.75 1.   1.75 3.25 3.25 3.5  2.5
 2.5  3.   4.   2.75 2.75 3.5  2.5  2.25 3.   3.   2.5  2.5  3.   3.5
 2.5  3.5  2.25 3.5  1.75 2.75 2.5  2.5  1.25 3.   4.   3.75 3.5  3.25
 2.5  2.5  2.75 1.5  3.   3.   3.5  2.25 3.   3.   3.5  2.75 4.   4.25
 3.5  2.   2.5  1.75 3.   3.25 3.25 2.   2.5  3.75 2.5  1.5  3.75 3.25
 2.75 3.5  4.25 3.   4.25 3.5  3.5  3.25 2.5  2.25 2.   2.75 3.25 2.
 2.75 3.75]


In [12]:
avg_mean = avg_per_emp.mean()
print(avg_mean)

2.9625


In [16]:
Employees = np.where(avg_per_emp >avg_mean)[0].tolist()
print(Employees)

[0, 1, 3, 5, 6, 7, 8, 10, 11, 12, 13, 16, 17, 18, 19, 20, 24, 25, 26, 29, 30, 33, 36, 37, 40, 41, 43, 45, 51, 52, 53, 54, 55, 60, 61, 62, 64, 65, 66, 68, 69, 70, 74, 75, 76, 79, 82, 83, 85, 86, 87, 88, 89, 90, 91, 96, 99]
