In [ ]:
'''Set 3 (Weather Monitoring System)
NumPy (Intermediate)
 A weather station stores hourly temperature readings for 7 days in a NumPy array of shape (7, 24).
Task:
Find the daily maximum and minimum temperature


Identify the day with the largest temperature variation


Replace outliers beyond ±2 standard deviations with the mean temperature
'''

In [30]:
import numpy  as np
temps = np.random.randint(0, 20 ,size = (7,24))
print(temps)

[[18  1  5 18  8  7 17 10  4 14 11 13 17  7 12  1  7  8 19  4 16  6  6  3]
 [18  2  0 16  3  1 12 15 16  0 11 15  6  1 18  9  6 16 12 15 11 14 19 14]
 [19 16 12 14  8  0  5  9  2  7 17 19 10 19  8  8  6  3  1 18  4 10  9 19]
 [19  8  9 14  7  1 14 15 18  7  0  6 15 19 13  1  2 14 13  9  8 19  4 14]
 [ 1 19 18 13  2 11 19  4  5  3  5  6  1 16  1  9  5 17 18  9 13  0  0  4]
 [11 11  1 15 11  0 10  8  9 19  5  7  3  4 16 14  3  0  4  5 16 14  0 19]
 [18 15 13 14  8 15  4 18  0  3 19  7  1 12 11 17 11  7  7  5  0 15  8 13]]


In [33]:
print(temps[0])
print(temps[1])

[18  1  5 18  8  7 17 10  4 14 11 13 17  7 12  1  7  8 19  4 16  6  6  3]
[18  2  0 16  3  1 12 15 16  0 11 15  6  1 18  9  6 16 12 15 11 14 19 14]


In [36]:
max = temps.max(axis =1)
print(max)
min = temps.min(axis =1)
print(min)

[19 19 19 19 19 19 19]
[1 0 0 0 0 0 0]


In [45]:
variation = max -min
day_largest_variation = np.argmax(variation)
print(variation)
print(day_largest_variation)

[18 19 19 19 19 19 19]
0


In [43]:
mean = temps.mean()
print(mean)
std = temps.std()
print(std)

9.636904761904763
6.086113776104717


In [44]:
lower = mean-2*std
upper = mean=2*std
print(upper)
print(lower)

12.172227552209433
-2.5353227903046704
