In [ ]:
'''Set 4 (Online Learning Platform)
NumPy (Intermediate)
 An online platform tracks time spent (in minutes) by students on 6 courses over 14 days using a NumPy array.
Task:
Compute total time spent per course


Identify courses where average daily engagement exceeds a threshold


Rank courses based on engagement
'''

In [3]:
import numpy as np
time_spent = np.random.randint(0,61,size=(14,6))
print(time_spent)

[[10 26  1 23 15 14]
 [ 0 46  0  9 46  0]
 [32 19 38 50 49 18]
 [50 32 16  4 35  0]
 [37 35 45 49  0 60]
 [ 0 59  5  1 53 18]
 [ 1 53 35 11 25 10]
 [44 35 15  5 36 31]
 [19  1 50 34  3 53]
 [40 51 47 30  3 57]
 [13 38 30  5 25 39]
 [45 27 22 20 20 29]
 [17 37 54 30 40 39]
 [ 9 24 52 39 60 49]]


In [4]:
total_time_spent_per_course = time_spent.sum(axis=0)
print(total_time_spent_per_course)

[317 483 410 310 410 417]


In [20]:
threshold = 25
avg_daily_eng = time_spent.mean(axis = 0)
print(avg_daily_eng)

[22.64285714 34.5        29.28571429 22.14285714 29.28571429 29.78571429]


In [21]:
high_course = np.where(avg_daily_eng > threshold)[0]+1
print(high_course)

[2 3 5 6]


In [24]:
ranked_courses = np.argsort(total_time_spent_per_course)[::-1]+1
print(ranked_courses)

[2 6 5 3 1 4]
