In [12]:
import numpy as np
x = np.array([[12,11,13],
              [21,25,20],
              [18,27,16]])
y = np.sort(x,axis=0)
print(y)

[[12 11 13]
 [18 25 16]
 [21 27 20]]


In [14]:
y1 = np.argsort(x,axis=0)
print(y1)

[[0 0 0]
 [2 1 2]
 [1 2 1]]


In [16]:
x = np.sort([7,2,3,9,6])
print(x)

[2 3 6 7 9]
