In [12]:
import numpy as np
x = np.array([[12,11,13],
              [21,25,20],
              [18,27,16]])
y = np.sort(x,axis=0)
print(y)

[[12 11 13]
 [18 25 16]
 [21 27 20]]


In [14]:
y1 = np.argsort(x,axis=0)
print(y1)

[[0 0 0]
 [2 1 2]
 [1 2 1]]


In [21]:
x = np.sort([7,2,3,9,6])[::-1]
print(x)

[9 7 6 3 2]


In [22]:
import numpy as np
x = np.array([4,2,3,9,7])
y = np.max(x)
print(y)

9


In [23]:
y = np.min(x)
print(y)

2


In [24]:
y = np.sum(x)
print(y)

25


In [25]:
y = np.mean(x)
print(y)

9


In [26]:
y = np.prod(x)
print(y)

1512


In [27]:
y = np.var(x)
print(y)

6.8


In [28]:
y = np.std(x)
print(y)

2.6076809620810595


In [29]:
y = np.median(x)
print(y)

4.0


In [30]:
print(np.full(5,7))

[7 7 7 7 7]


In [31]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [32]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [33]:
print(a.size)

6


In [34]:
print(a.dtype)

int64


In [35]:
print(a.itemsize)

8


In [40]:
print(a.ndim)

2


In [38]:
print(a.reshape(2,3))


[[1 2 3]
 [4 5 6]]


In [39]:
print(a.flatten())

[1 2 3 4 5 6]


In [43]:
print(a[a>3])

[4 5 6]


In [46]:
print(a[(a>3) & (a<5)])

[4]


In [48]:
a = np.array([[1,2,3],[4,5,6]])
print(a+10)

[[11 12 13]
 [14 15 16]]


In [49]:
b = np.array([10,20,30])

In [50]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [51]:
a = np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [52]:
b = a[1:3]
b[0] =100
print(a)

[  1 100   3   4]


In [53]:
b = np.array([8,7,4,5,3])
a = b[2:5]
a[1] = 200
print(b)

[  8   7   4 200   3]


In [56]:
a = np.array([1,2,3,4])
b = a[1:3].copy()
b[0] = 100
print(a)
print(b)
print(a)

[1 2 3 4]
[100   3]
[1 2 3 4]


In [61]:
a = np.array([2,4])
b = np.array([3,5])

print(np.concatenate((a,b)))

[2 4 3 5]


In [66]:
print(np.stack((a,b)))
print(np.vstack((a,b)))

[[2 4]
 [3 5]]
[[2 4]
 [3 5]]


In [68]:
print(np.hstack((a,b)))

[2 4 3 5]


In [70]:
print(a+b)

[5 9]


In [79]:
c = np.array([1,2,3,4,5,6])
print(np.split(c,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [81]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [87]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a@b)
print(np.dot(a,b))
print(a.T)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [90]:
a = np.array([[2,1],[1,2]])
print(np.linalg.det(a))
print(np.linalg.inv(a))

2.9999999999999996
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


In [92]:
a = np.array([10,20,30,40,50])
print(np.median(a))
print(np.percentile(a,50))

30.0
30.0


In [95]:
a = np.array([1,2,np.nan,4])
print(np.isnan(a))
print(np.nanmean(a))

[False False  True False]
2.3333333333333335


In [97]:
a = np.array([1,1,2,3,2,2,])
print(np.unique(a))

[1 2 3]


In [98]:
a = np.array([1,10,20,30])
print(np.clip(a,5,25))

[ 5 10 20 25]
