In [1]:
import numpy as np
array1 = np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [7]:
array1 = np.arange(11,20).reshape((3,3))
print(array1)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [10]:
array1 = np.zeros((4,2))
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
array1 = np.ones((2,3))
print(array1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
list2 = [[10,20,30,40,50],[7,9,2,3,4],[5,3,3,4,5]]
array2 = np.array(list2)
array2.itemsize


8

In [39]:
list3 = [[10,20,30,40,50],[7,9,2,3,4],[5,3,3,4,5]]
array3 = np.array(list3)
print(array3[0,4])

50


In [40]:
print(array3[:,1])

[20  9  3]


In [41]:
print(array3[2,:])

[5 3 3 4 5]


In [42]:
print(array3[1:3])

[[7 9 2 3 4]
 [5 3 3 4 5]]


In [45]:
print(array3[1:6:2])

[[7 9 2 3 4]]


In [47]:
array4 = np.array([10,20,30,40,50,60,70])
print(array4[1:6])

[20 30 40 50 60]


In [48]:
print(array4[1:6:2])

[20 40 60]


In [62]:
print(array4[-1:-8:-1])

[70 60 50 40 30 20 10]


In [63]:
print(array4[::2])

[10 30 50 70]


In [64]:
print(array4[::-1])

[70 60 50 40 30 20 10]


In [79]:
array5 = [[15,16,17],[25,26,27],[35,36,37],[45,46,47]]
arr = np.array(array5)
print(arr)
# print(arr[:,1])
# print(arr[1,])
# print(arr[1:3,1:3])
# print(arr[:,1:3])
# print(arr[1:3,1])
# print(arr[1:3,:1])
# print(arr[1:3,1:])
print(arr[0:2,1:3])

[[15 16 17]
 [25 26 27]
 [35 36 37]
 [45 46 47]]
[[16 17]
 [26 27]]


In [92]:
x = np.array([[1,2],[3,4]])
y = np.array([[11,12],[13,14]])
# z= y@x
#z= y/x
# z = y**x
z = x.transpose()
print(z)


[[1 3]
 [2 4]]
